name: mjdocker

channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8
 - ipython
 - numpy
 - scipy
 - patchelf #for mujoco
 - pip
 - pip:
    # regular pip dependencies	
    - free-mujoco-py
